### ISSUE TITLE
Not staying connected

### ISSUE THREAD

**Issue by mme89** [dubbadhar/PCHWRM_Server#12]
Hi,
thanks for your work!

I can run the server and client without any issues, but the connection between the two doesn't stay on. The client connects and GUI is showing everything, but just for a second and then its gone. Here is what the server side tells:

`Starting Server ...
... Done!
Listening for Clients on 192.168.22.131
... Connected!
java.lang.NumberFormatException: For input string: "3,954765"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(Unknown Source)
	at java.base/java.lang.Double.parseDouble(Unknown Source)
	at PCHWRMServer.monitor.dataReceived(monitor.java:165)
	at PCHWRMServer.monitor$2.call(monitor.java:98)
	at PCHWRMServer.monitor$2.call(monitor.java:75)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Message : CPU_GPU_MODELS!!    Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz  ::Name                     NVIDIA GeForce GTX 1080  ::
Message : PC_DATA!!CPU_TEMP<>46::GPU_LOAD<>0::USED_RAM<>3,931095::USED_VRAM<>392,0273::CPU_FAN<>558,3127::FREE_RAM<>28,02365::CPU_LOAD<>23,04688::TOTAL_VRAM<>8192::GPU_TEMP<>46::
B
Starting Server ...
... Done!
Listening for Clients on 192.168.22.131`

It seems like, as soon as the connection is made, the der is starting again on its own.

Thanks

**Comment by phiomet** [comment]
Hello,

same here on my Raspian Buster Pi 3:

`java.lang.NumberFormatException: For input string: "6,642555"
Message : CPU_GPU_MODELS!!  AMD Ryzen 7 1700X Eight-Core Processor  ::Name                     NVIDIA GeForce GTX 1080  ::
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(Unknown Source)
        at java.base/java.lang.Double.parseDouble(Unknown Source)
        at PCHWRMServer.monitor.dataReceived(monitor.java:164)
        at PCHWRMServer.monitor$2.call(monitor.java:98)
        at PCHWRMServer.monitor$2.call(monitor.java:75)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Message : PC_DATA!!FREE_RAM<>6,644421::TOTAL_VRAM<>8192::GPU_TEMP<>64::CPU_LOAD<>5,67646::GPU_FAN<>1390::USED_VRAM<>1592,902::CPU_FAN<>795,053::USED_RAM<>9,273994::GPU_LOAD<>0::CPU_TEMP<>35::
B
`

**Comment by Always666** [comment]
That issue is because of the decimal separator on the OS of the client is set to "," instead of "." its already reported in the issues on the client github section.

**Comment by phiomet** [comment]
> 
> 
> That issue is because of the decimal separator on the OS of the client is set to "," instead of "." its already reported in the issues on the client github section.

Nice! Workaround helps. Thank you
