### ISSUE TITLE
Stacktrace on client connection java.lang.NumberFormatException: For input string: "7,807262"

### ISSUE THREAD

**Issue by Doooooo0o** [dubbadhar/PCHWRM_Server#20]
Feel free to ask if you need anymore info or tests! I've ran it on a fresh raspberry setup 

```bash
$ uname -a
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
$ java --version
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Raspbian-3deb10u1)
OpenJDK Server VM (build 11.0.7+10-post-Raspbian-3deb10u1, mixed mode)
```

Here is the full server stack and behaviour:

```java
Starting Server ...
... Done!
Listening for Clients on 192.168.1.246
... Connected!
java.lang.NumberFormatException: For input string: "7,807262"
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(Unknown Source)
        at java.base/java.lang.Double.parseDouble(Unknown Source)
        at PCHWRMServer.monitor.dataReceived(monitor.java:164)
        at PCHWRMServer.monitor$2.call(monitor.java:98)
        at PCHWRMServer.monitor$2.call(monitor.java:75)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Message : CPU_GPU_MODELS!!    Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz  ::   NVIDIA GeForce RTX 2070 SUPER  ::
Message : PC_DATA!!TOTAL_VRAM<>8192::GPU_TEMP<>38::GPU_LOAD<>9::FREE_RAM<>7,956665::CPU_LOAD<>16,04043::USED_VRAM<>3197,09::GPU_FAN<>1123::USED_RAM<>7,963619::CPU_TEMP<>39::
B
Starting Server ...
... Done!
Listening for Clients on 192.168.1.246

```
Resulting on a cycle display with some graphs and back to "listening for connections"

On the client side: nothing much after clicking on "connect"

**Comment by rnayabed** [comment]
Can you try changing your region from europe to perhaps US? This is probably because `,` is being uses instead of `.`

**Comment by rnayabed** [comment]
Re-open if the problem exists

**Comment by Doooooo0o** [comment]
I feel like I shouldn't have to tweak my OS for this :-) 

I'll stick with my openhardwaremonitor + https://github.com/nickbabcock/OhmGraphite setup which seems to be less restrictive.

**Comment by rnayabed** [comment]
> I feel like I shouldn't have to tweak my OS for this :-)
> 
> I'll stick with my openhardwaremonitor + https://github.com/nickbabcock/OhmGraphite setup which seems to be less restrictive.

sure, that sounds good. also take a look at modbros if possible
