### ISSUE TITLE
GUI does not load

### ISSUE THREAD

**Issue by bitc0de** [dubbadhar/PCHWRM_Server#3]
I am doing the whole process with a clean install of Raspbian, and it connects with the client correctly.
But the graphics are not seen.

Do I have to install something else? Maybe it's from javafx?
Thank you

![image](https://user-images.githubusercontent.com/3879848/79669399-7f21a400-81bb-11ea-851c-e3533b76b219.png)

pi@raspberrypi:~/Downloads/PCHWRM_Server $  ./run
JavaFX launchApplication method: launchMode=LM_CLASS
Prism pipeline init order: es2 
Using Double Precision Marlin Rasterizer
Using dirty region optimizations
Using system sized mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.es2.ES2Pipeline
Loading ES2 native library ... prism_es2_monocle
System.loadLibrary(prism_es2_monocle) succeeded
	succeeded.
GLFactory using com.sun.prism.es2.MonocleGLFactory
System.loadLibrary(glass_monocle) succeeded
(X) Got class = class com.sun.prism.es2.ES2Pipeline
Initialized prism pipeline: com.sun.prism.es2.ES2Pipeline
JavaFX: using com.sun.javafx.tk.quantum.QuantumToolkit
Maximum supported texture size: 2048
Non power of two texture support = true
Maximum number of vertex attributes = 8
Maximum number of uniform vertex components = 544
Maximum number of uniform fragment components = 544
Maximum number of varying components = 32
Maximum number of texture units usable in a vertex shader = 8
Maximum number of texture units usable in a fragment shader = 8
Graphics Vendor: Broadcom
       Renderer: VideoCore IV HW
        Version: OpenGL ES 2.0
 vsync: true vpipe: true
WARNING: Cannot access application main method: java.lang.NoSuchMethodException: PCHWRMServer.Main.main([Ljava.lang.String;)
Launching application directly
System.loadLibrary(javafx_font) succeeded
System.loadLibrary(javafx_font_freetype) succeeded
System.loadLibrary(javafx_font_pango) succeeded
C
Starting Server ...
... Done!
Listening for Clients on 192.168.1.103
... Connected!
Message : CPU_GPU_MODELS!! Intel(R) Xeon(R) CPU E31245 @ 3.30GHz  :: Radeon (TM) RX 480 Graphics  ::
Message : PC_DATA!!GPU_LOAD<>0::USED_RAM<>4,980942::GPU_TEMP<>50::CPU_LOAD<>9,570313::FREE_RAM<>10,97708::CPU_TEMP<>53::
B
Starting Server ...
... Done!
Listening for Clients on 192.168.1.103
max rectangle texture cell size = 62
wrap rectangle texture = 2 x 2
ES2ResourceFactory: Prism - createStockShader: AlphaTexture_Color.frag
ES2ResourceFactory: Prism - createStockShader: Texture_Color.frag
ES2ResourceFactory: Prism - createStockShader: FillRoundRect_Color.frag
new alphas with length = 4096
ES2ResourceFactory: Prism - createStockShader: Solid_TextureRGB.frag
new alphas with length = 36864
ES2ResourceFactory: Prism - createStockShader: AlphaOne_Color.frag
ES2ResourceFactory: Prism - createStockShader: DrawRoundRect_Color.frag
ES2ResourceFactory: Prism - createStockShader: FillCircle_Color.frag
ES2ResourceFactory: Prism - createStockShader: DrawCircle_Color.frag
new alphas with length = 49152

**Comment by evargre** [comment]
I had not connected any screen .. and I have seen that JavaFX needs it ..
Now I have connected it and the error is:

...
Starting Server ...
... Done!
Listening for Clients on 192.168.1.103
max rectangle texture cell size = 62
wrap rectangle texture = 2 x 2
ES2ResourceFactory: Prism - createStockShader: AlphaTexture_Color.frag
ES2ResourceFactory: Prism - createStockShader: Texture_Color.frag
ES2ResourceFactory: Prism - createStockShader: FillRoundRect_Color.frag
new alphas with length = 4096
ES2ResourceFactory: Prism - createStockShader: Solid_TextureRGB.frag
new alphas with length = 36864
ES2ResourceFactory: Prism - createStockShader: AlphaOne_Color.frag
glGetError 0x505
glGetError 0x505
glGetError 0x505
glGetError 0x505
glGetError 0x505
glGetError 0x505
ES2ResourceFactory: Prism - createStockShader: DrawRoundRect_Color.frag
Program link log: 
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.graphics/com.sun.prism.es2.ES2ResourceFactory.createStockShader(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.getPaintShader(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.validatePaintOp(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.validatePaintOp(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedPgram(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedRect(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.drawRoundRect(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderBorderRectangle(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderAsRectangle(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.CacheFilter.renderNodeToCache(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.CacheFilter.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderCached(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.doPaint(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.paintImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.PresentingPainter.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.RenderJob.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Error creating shader program
	at javafx.graphics/com.sun.prism.es2.ES2Shader.createFromSource(Unknown Source)
	at javafx.graphics/com.sun.prism.es2.ES2Shader.createFromSource(Unknown Source)
	at javafx.graphics/com.sun.prism.es2.ES2ResourceFactory.createShader(Unknown Source)
	at javafx.graphics/com.sun.prism.shader.DrawRoundRect_Color_Loader.loadShader(Unknown Source)
	... 53 more
java.lang.InternalError: Error loading stock shader DrawRoundRect_Color
	at javafx.graphics/com.sun.prism.es2.ES2ResourceFactory.createStockShader(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.getPaintShader(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.validatePaintOp(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.validatePaintOp(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedPgram(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedRect(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.drawRoundRect(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderBorderRectangle(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderAsRectangle(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.CacheFilter.renderNodeToCache(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.CacheFilter.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderCached(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.doPaint(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.paintImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.PresentingPainter.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.RenderJob.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
glGetError 0x505
ES2ResourceFactory: Prism - createStockShader: DrawRoundRect_Color.frag
Program link log: 
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.graphics/com.sun.prism.es2.ES2ResourceFactory.createStockShader(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.getPaintShader(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.validatePaintOp(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.validatePaintOp(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedPgram(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedRect(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.drawRoundRect(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderBorderRectangle(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderAsRectangle(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.CacheFilter.renderNodeToCache(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.CacheFilter.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderCached(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.doPaint(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.paintImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.PresentingPainter.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.RenderJob.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Error creating shader program
	at javafx.graphics/com.sun.prism.es2.ES2Shader.createFromSource(Unknown Source)
	at javafx.graphics/com.sun.prism.es2.ES2Shader.createFromSource(Unknown Source)
	at javafx.graphics/com.sun.prism.es2.ES2ResourceFactory.createShader(Unknown Source)
	at javafx.graphics/com.sun.prism.shader.DrawRoundRect_Color_Loader.loadShader(Unknown Source)
	... 53 more
java.lang.InternalError: Error loading stock shader DrawRoundRect_Color
	at javafx.graphics/com.sun.prism.es2.ES2ResourceFactory.createStockShader(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.getPaintShader(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.validatePaintOp(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.validatePaintOp(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedPgram(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedRect(Unknown Source)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.drawRoundRect(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderBorderRectangle(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderAsRectangle(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.CacheFilter.renderNodeToCache(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.CacheFilter.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderCached(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.doPaint(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.ViewPainter.paintImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.PresentingPainter.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.RenderJob.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by evargre** [comment]
the problem is the memory of RPi.
I have expanded the memory of RPi to 256 from raspi-config / Advanced Options / Memory Split
